name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "13 8 * * *" # 8:13 AM UTC is 12:13 AM PT

jobs:
  update:
    name: Update root DNS cache
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1

      - name: Update root cache
        run: go generate -v -x

      - name: Vet Go code
        run: go vet ./...

      - name: Run Go tests
        run: go test -mod=readonly -v -race ./...

      - name: Commit changes
        run: |
          [[ -z $(git status -s) ]] || (
            git config --global user.email robot@zonedb.org
            git config --global user.name zonedbot
            git add -v --all .
            git commit -m "Automatic update for `date -u`"
            git push origin -u HEAD
          )
